'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CheckCircle2, CreditCard, Loader2, Shield, Smartphone, Sparkles } from 'lucide-react';
import { supabase } from '@/lib/supabase';

export default function PersonalSetup() {
  const [state,setState]=useState<any>(null); const [device,setDevice]=useState(''); const [loading,setLoading]=useState(true);
  useEffect(()=>{void (async()=>{const {data}=await supabase.auth.getSession(); if(!data.session){setLoading(false);return} const h={Authorization:`Bearer ${data.session.access_token}`}; const [p,d]=await Promise.all([fetch('/api/personal',{headers:h}),fetch('/api/personal/devices',{headers:h})]); setState(await p.json()); const db=await d.json(); setDevice(db.devices?.find((x:any)=>x.status==='ACTIVE')?.id??localStorage.getItem('horus-personal-device-id')??''); setLoading(false)})()},[]);
  if(loading)return <div className="h-full flex items-center justify-center bg-[#050508] text-white/50"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Sincronizando configuração…</div>;
  if(!state?.profile)return <div className="h-full bg-[#050508] text-white p-8"><div className="max-w-2xl mx-auto"><Link href="/dashboard/personal" className="text-xs text-white/50 flex items-center gap-2"><ArrowLeft className="h-4 w-4"/>Voltar ao Personal</Link><div className="mt-16 rounded-3xl border border-white/10 bg-[#090A0F] p-8 text-center"><CreditCard className="mx-auto h-10 w-10 text-amber-400"/><h1 className="mt-4 text-2xl font-black">Configuração disponível após ativação</h1><p className="mt-2 text-sm text-white/45">A configuração operacional só pode ser persistida quando o Billing reconhecer uma subscription ACTIVE.</p><Link href="/dashboard/personal" className="mt-6 inline-flex rounded-xl bg-amber-500 px-5 py-3 text-xs font-black text-black">Voltar ao Personal</Link></div></div></div>;
  const active=state.subscription?.status==='ACTIVE';
  return <div className="h-full overflow-y-auto bg-[#050508] text-white p-6 sm:p-10"><div className="max-w-4xl mx-auto space-y-6"><div className="flex items-center justify-between"><Link href="/dashboard/personal" className="text-xs text-white/50 flex items-center gap-2"><ArrowLeft className="h-4 w-4"/>Personal</Link><span className="text-[10px] font-bold uppercase tracking-widest text-emerald-400">Runtime conectado</span></div><header className="rounded-3xl border border-white/10 bg-[#090A0F] p-7"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-amber-400">Configuração real</p><h1 className="mt-2 text-3xl font-black">Hórus Personal</h1><p className="mt-2 text-sm text-white/45">Esta tela reflete o estado persistido pelo backend; não cria contratação, persona ou permissões fictícias.</p></header><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#090A0F] p-5"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-amber-400"/><div><p className="text-sm font-bold">Persona</p><p className="text-xs text-white/40">{state.personas?.find((p:any)=>p.id===state.profile.persona_id)?.display_name??state.profile.persona_id}</p></div><CheckCircle2 className="ml-auto h-4 w-4 text-emerald-400"/></div></div><div className="rounded-2xl border border-white/10 bg-[#090A0F] p-5"><div className="flex items-center gap-3"><CreditCard className="h-5 w-5 text-amber-400"/><div><p className="text-sm font-bold">Subscription</p><p className="text-xs text-white/40">{state.subscription?.status??'Sem assinatura'} · {state.subscription?.tier??'—'}</p></div>{active&&<CheckCircle2 className="ml-auto h-4 w-4 text-emerald-400"/>}</div></div><div className="rounded-2xl border border-white/10 bg-[#090A0F] p-5"><div className="flex items-center gap-3"><Smartphone className="h-5 w-5 text-blue-400"/><div><p className="text-sm font-bold">Device Binding</p><p className="text-xs text-white/40">{device?'Dispositivo ativo':'Nenhum dispositivo ativo'}</p></div>{device&&<CheckCircle2 className="ml-auto h-4 w-4 text-emerald-400"/>}</div></div><div className="rounded-2xl border border-white/10 bg-[#090A0F] p-5"><div className="flex items-center gap-3"><Shield className="h-5 w-5 text-purple-400"/><div><p className="text-sm font-bold">Autoridade</p><p className="text-xs text-white/40">Auth + Subscription + Capability governam execução</p></div></div></div></div><div className="flex flex-wrap gap-3"><Link href="/dashboard/personal/voice" className="rounded-xl bg-blue-500 px-5 py-3 text-xs font-black text-white">Abrir Voice Runtime</Link><Link href="/dashboard/personal/companion" className="rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-xs font-bold">Desktop Companion</Link></div></div></div>;
}
