'use client';
import { BrainCircuit, Sparkles, Database, Users, X, Menu, ArrowLeft, Settings, Target, UserRound } from 'lucide-react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { ChevronRight } from 'lucide-react';

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname() ?? '';
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  if (pathname === '/dashboard/studio' || pathname.startsWith('/dashboard/studio/')) {
    return <>{children}</>;
  }

  const navItems = [
    { name: 'Nexus', href: '/nexus', icon: BrainCircuit },
    { name: 'Hórus Operations™', href: '/dashboard', icon: Target },
    { name: 'Hórus Personal · Minha Operação Pessoal', href: '/dashboard/personal', icon: UserRound },
    { name: 'Studio Hórus™', href: '/dashboard/studio', icon: Sparkles },
    { name: 'Equipes Cognitivas™', href: '/dashboard/agents', icon: Users },
    { name: 'Memory Graph™', href: '/dashboard/memory', icon: Database },
  ];
  const isPersonal = pathname === '/dashboard/personal' || pathname.startsWith('/dashboard/personal/');
  return <div className="h-screen w-full flex bg-[#080808] text-[#FAFAFA] font-sans overflow-hidden">
    <div className="lg:hidden fixed top-0 left-0 right-0 h-16 border-b border-[#1C1C1C] bg-[#101010]/95 backdrop-blur-xl z-30 flex items-center justify-between px-4"><button onClick={() => setIsSidebarOpen(true)} className="p-2 -ml-2 text-[#FAFAFA]/70"><Menu className="w-5 h-5" /></button><div className="flex items-center gap-2"><BrainCircuit className="w-5 h-5 text-[#D4AF37]" /><span className="font-extrabold text-xs tracking-[0.2em]">HÓRUS OS</span></div><div className="w-9" /></div>
    {isSidebarOpen && <div className="fixed inset-0 bg-[#080808]/80 z-40 lg:hidden backdrop-blur-sm" onClick={() => setIsSidebarOpen(false)} />}
    <aside className={`fixed lg:static inset-y-0 left-0 z-40 w-72 bg-[#101010]/95 border-[#1C1C1C] backdrop-blur-2xl border-r flex flex-col transition-transform duration-300 ease-in-out ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}`}>
      <div className="h-20 flex items-center px-6 border-b border-[#1C1C1C] shrink-0"><Link href="/dashboard" className="flex items-center gap-3 group"><div className="w-10 h-10 rounded-xl bg-[#D4AF37]/10 flex items-center justify-center border border-[#D4AF37]/20"><BrainCircuit className="w-6 h-6 text-[#D4AF37]" /></div><div><span className="font-extrabold text-lg tracking-[0.2em]">HÓRUS OS</span><span className="block text-[10px] text-[#FAFAFA]/40 uppercase tracking-[0.3em] font-bold">Mission Control</span></div></Link></div>
      <div className="p-4 border-b border-[#1C1C1C] shrink-0 relative"><div className="text-[10px] text-[#FAFAFA]/40 font-bold uppercase tracking-[0.2em] mb-2 px-1">Hórus Workspaces™</div><div className="group relative"><div className="bg-[#141414] border border-[#1C1C1C] rounded-xl p-3 flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-gradient-to-tr from-[#D4AF37] to-[#E5D2A0] p-[1px] shrink-0"><div className="w-full h-full bg-[#080808] rounded-full flex items-center justify-center"><span className="text-sm font-bold text-[#D4AF37]">NC</span></div></div><div className="flex-1 overflow-hidden"><h4 className="font-bold text-sm truncate">Nexus Corp</h4><p className="text-[9px] text-[#C9A55C] font-bold uppercase tracking-[0.2em]">Operação Enterprise</p></div><ChevronRight className="w-4 h-4 text-white/30" /></div><div className="absolute top-full left-0 mt-2 w-full bg-[#101010] border border-[#1C1C1C] rounded-xl shadow-2xl opacity-0 scale-95 pointer-events-none group-hover:opacity-100 group-hover:scale-100 group-hover:pointer-events-auto transition-all z-50 overflow-hidden"><div className="p-3 border-b border-[#1C1C1C]"><p className="text-[9px] font-bold text-white/40 uppercase tracking-[0.2em]">Hórus Workspaces™</p></div><div className="p-2 space-y-1"><button className="w-full flex items-center gap-3 p-2 rounded-lg bg-[#141414] border border-[#D4AF37]/30 text-left"><span className="text-xs font-bold">Nexus Corp</span></button><Link href="/dashboard/personal" onClick={() => setIsSidebarOpen(false)} className={`w-full flex items-center gap-3 p-2 rounded-lg border text-left transition-colors ${isPersonal ? 'bg-[#141414] border-[#D4AF37]/30 text-white' : 'border-transparent text-white/50 hover:text-white hover:bg-[#141414]'}`}><div className="w-8 h-8 rounded-full bg-[#1A1A1A] border border-[#2A2A2A] flex items-center justify-center shrink-0"><span className="text-xs font-bold">OP</span></div><div><p className="text-xs font-bold">Minha Operação Pessoal</p><p className="text-[8px] text-[#D4AF37] uppercase tracking-wider">Personal</p></div></Link><button className="w-full flex items-center gap-3 p-2 rounded-lg hover:bg-[#141414] border border-transparent text-left text-white/40"><span className="text-xs font-bold">Minha Clínica</span></button><button className="w-full flex items-center gap-3 p-2 rounded-lg hover:bg-[#141414] border border-transparent text-left text-white/40"><span className="text-xs font-bold">Restaurante Imperial</span></button></div></div></div></div>
      <nav className="flex-1 overflow-y-auto custom-scrollbar py-4 px-3 space-y-1">{navItems.map((item) => { const active = pathname === item.href || pathname.startsWith(`${item.href}/`); return <Link key={item.name} href={item.href} onClick={() => setIsSidebarOpen(false)} aria-label={item.href === '/dashboard/personal' ? 'Hórus Personal' : item.name} className={`flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all text-xs tracking-wide font-medium ${active ? 'bg-[#D4AF37]/10 text-[#D4AF37] border border-[#D4AF37]/20' : 'text-white/60 hover:text-white hover:bg-[#141414] border border-transparent'}`}><item.icon className={`w-4 h-4 ${active ? 'text-[#D4AF37]' : 'text-white/40'}`} />{item.name}</Link>})}</nav>
      <div className="p-4 border-t border-[#1C1C1C] shrink-0 space-y-2"><Link href="/dashboard/settings" className="flex items-center gap-3 px-3 py-2.5 rounded-lg text-white/60 hover:text-white hover:bg-[#141414] text-xs font-medium"><Settings className="w-4 h-4 text-white/40" />Configurações Globais</Link><Link href="/" className="flex items-center gap-3 px-3 py-2.5 rounded-lg text-white/60 hover:text-[#D4AF37] hover:bg-[#D4AF37]/10 text-xs font-medium"><ArrowLeft className="w-4 h-4 text-[#D4AF37]/50" />Sair do Console (Home)</Link></div><button className="lg:hidden p-2 text-white/50 absolute right-4 top-6" onClick={() => setIsSidebarOpen(false)}><X className="w-5 h-5" /></button>
    </aside><main className="flex-1 relative z-10 flex flex-col bg-[#080808] min-w-0 min-h-0 overflow-hidden pt-16 lg:pt-0">{children}</main>
  </div>;
}